### ISSUE TITLE
Bricked Camera

### ISSUE THREAD

**Issue by pumplerod** [iamagod/Authydra#2]
Installed the plugin.  Started taking photos, lost power, now the camera will not power on.  Each time I try to turn on the power I get "Error!" and the camera shuts off.

**Comment by iamagod** [comment]
hmmm strange. Do you still have the issue? Did you look at the forum at the options on resetting the camera?

Let me know!

**Comment by doppioslash** [comment]
I had the same, in the end the camera (Z1) did boot properly again. I had to hard-reset the camera a couple times.

**Comment by pumplerod** [comment]
I was able to finaly get the camera to reset, however there now seems to be an extra folder on the camera storage system with the HDR images test in it. There seems to be no way to remove this folder or the images in them. Ricoh says the only way to delete files is through their (very poor) iPhone app. And that there is no way to mount the camera's storage to my computer. As great as the camera is, it would seem they went out of their way to cripple its usability. 

-t

**Comment by doppioslash** [comment]
@pumplerod the same happened to me too. I don't know what camera you have, but if it is a Z1 you can mount the camera drive on a windows pc.

**Comment by iamagod** [comment]
in the authydra app there is a file manage section, in their you should be able to delete folders and other files. 
I hope that can help.
